export { default as classMapMerge } from './classMapMerge'
export { default as simpleApiCall } from './simpleApiCall'
export { default as getEthereumGasEstimate } from './getEthereumGasEstimate'
export { default as timeDiffToWords } from './timeDiffToWords'
export { default as dateStringDiffToWords } from './dateStringDiffToWords'